### ISSUE TITLE
Game refuses to start only when ShulkerBoxTooltip is installed

### ISSUE THREAD

**Issue by greenghost110** [MisterPeModder/ShulkerBoxTooltip#120]
#### Steps to reproduce:

1. Use Forge 45.0.66 on MC 1.19.4
2. Use the latest version of ShulkerBoxTooltip (3.3.0+1.19.4 as of now)
3. Use the latest version of cloth config (10.0.96 as of now)
4. Attempt to launch game with two mods
5. Game crashes 

____
#### Affected Versions (Do *not* use "latest"):

- Forge 45.0.66
- ShulkerBoxTooltip: 3.3.0+1.19.4
- Minecraft: 1.19.4
- Other mods (if relevant): Cloth Config 10.0.96

#### Your most recent log file where the issue was present: 

https://pastebin.com/D2VSimHL

**Comment by MisterPeModder** [comment]
Hello, sorry for the late fix,
It took me a while to identify the cause because I was running an older build of Forge in my development environment.
The crash occurred because the mod was patching a method that was overwritten in newer Force 1.19.4 versions.
The patch should be available for download at Curseforge or Modrinth shortly.

**Comment by MisterPeModder** [comment]
You may download the fix over at [Curseforge](https://legacy.curseforge.com/minecraft/mc-mods/shulkerboxtooltip/files/4567677) or [Modrinth](https://modrinth.com/mod/shulkerboxtooltip/version/3.3.1+1.19.4-forge).
