### ISSUE TITLE
Open Full Stack Key Not Working

### ISSUE THREAD

**Issue by SandmansDreams** [MisterPeModder/ShulkerBoxTooltip#124]
When trying to view contents of shulker boxes, the Full Stack key does not function and shows as unbound. It does activate, removing the "n stacks" tooltip, but does not bring up visuals. The Partial Stack key does work fine. 
![Screenshot 2023-06-11 102107](https://github.com/MisterPeModder/ShulkerBoxTooltip/assets/71186324/7b7be82a-74cc-4c30-a05f-16603cbb7687)
![Screenshot 2023-06-11 102206](https://github.com/MisterPeModder/ShulkerBoxTooltip/assets/71186324/539bc8d8-98f1-46e7-8245-a404ddae793c)

**Comment by MisterPeModder** [comment]
I think you have the "Swap Modes" option turned on.
The reason the tooltip has "Not Bound" in the image is because you still need to press the regular "Open Stack Preview" key (shift, by default) to open the preview even when the modes are swapped.

You can enable "Always On"  if you wish to not bind the "Open Stack Preview" key.

However, the "Contains N stacks" line hiding itself when pressing the "Full Preview" key *is* a bug and will by patched by the 3.4.0 version for Minecraft 1.19.4 and by the 4.0.3 version for Minecraft 1.20-1.20.1

I'm closing this issue for now. If you have any questions feel free to ask!
