### ISSUE TITLE
game cant launch with mod

### ISSUE THREAD

**Issue by Jacktatt99** [MisterPeModder/ShulkerBoxTooltip#56]
#### Issue Description: the game cannot launch with this mod

Delete this line after reading it: If this bug occurs in a modpack, please report this to the modpack author first.

#### What happens:
the launcher crashes and displays: 
"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'shulkerboxtooltip'!
Exit Code: -1"

any idea? been looking for a shulker preview for ages!!! thanks tho

**Comment by MisterPeModder** [comment]
Please provide more information about your crash, such as the log and installed mods and Minecraft version

**Comment by GreemDev** [comment]
I have the same issue on 1.17; here's [the full crash report](https://paste.greemdev.net/imurirusukeyitozuqowafufotuhel.txt).
~~Yeah, I have other mods, but I figured I'd see if there was an open issue and this issue is the exact error, granted the second string in the error message in their error is `shulkerboxtooltip` and mine is `fabric-networking-v0`.~~
In the crash report, the only packages I see are for the Java standard library, Sponge, Fabric, and the ShulkerBoxTooltip project package; ~~which leads me to believe it's not another mod.~~

**Comment by GreemDev** [comment]
Appears I spoke too soon. Upon launching the game without this mod I got the same error and the error now doesn't even contain any ShulkerBoxTooltip packages. I'll need to do some more messing around.

Edit: The culprit appears to be the Carpet mod. (Maybe because I used the 1.17.1 version because I assumed it was compatible?)
It's still strange that we had the same issue.
